### ISSUE TITLE
Sprint 1 Milestone Tasks

### ISSUE THREAD

**Issue by L3viathon** [FullSol/amplifier#12]
- [ ] `git pull` your dev branch.
- [ ] [Review API Documentation](https://p2amplifier.docs.apiary.io/#)
- [ ] Review Git branching guidelines
- [ ] Complete issues by our next sprint
- [ ] Read/Practice examples of String Boot, Restful API, Sprint testing
- [ ] Familarize yourself with "user" stories & tables
