### ISSUE TITLE
Sprint 1 Milestone Tasks

### ISSUE THREAD

**Issue by L3viathon** [FullSol/amplifier#13]
- [x] `git pull` your dev branch.
- [x] [Review API Documentation](https://p2amplifier.docs.apiary.io/#)
- [x] Review Git branching guidelines
- [x] Complete issues by our next sprint
- [x] Read/Practice examples of String Boot, Restful API, Sprint testing
- [x] Familarize yourself with "user" stories & tables
