### ISSUE TITLE
Sprint 1 Milestone Tasks:

### ISSUE THREAD

**Issue by L3viathon** [FullSol/amplifier#15]
- [x] `git pull` your dev branch.
- [x] [Review API Documentation](https://p2amplifier.docs.apiary.io/#)
- [x] Read/Practice examples of String Boot, Restful API, Sprint testing
- [x] Update Git Branching Documentation for Patrick (Start Review; closes #; merging)
- [x] CI/CD pipelines will use AWS (CodePipeline, CodeBuild, Elastic Beanstalk, and S3)
