### ISSUE TITLE
Sprint 1 Milestone Tasks: 

### ISSUE THREAD

**Issue by L3viathon** [FullSol/amplifier#16]
- [x] `git pull` your dev branch.
- [x] [Update API Documentation](https://p2amplifier.docs.apiary.io/#)
- [x] Read/Practice examples of String Boot, Restful API, Sprint testing
- [x] CI/CD pipelines will use AWS (CodePipeline, CodeBuild, Elastic Beanstalk, and S3)
